### ISSUE TITLE
Passive mode does not work / Undocumented

### ISSUE THREAD

**Issue by nuKs** [andriykohut/docker-pyftpdlib#2]
Passive mode does not work / is undocumented.

You at least need to add the passive port range in your docker run -p attribute (ie `-p 3000-3010:3000-3010`).

Not enough for me though.

**Comment by andriykohut** [comment]
@nuKs Good point. You can define a custom port range if needed though: https://github.com/andriykohut/docker-pyftpdlib/pull/1, but as you said, these are not exposed.

I'm not sure about exposing the default range, but feel free to open the PR if you think it's useful to have this by default, otherwise it should be fairly easy to extend this image with custom `Dockerfile` or use another image which does this: https://github.com/stilliard/docker-pure-ftpd/blob/master/Dockerfile#L65

**Comment by nuKs** [comment]
Hi, thanks for the quick reply.

I was more thinking about documenting it.
https://github.com/andriykohut/docker-pyftpdlib/pull/3

However it didn't work either for me, but maybe I did something wrong. I tried another docker image and it worked.
